### Get 100 most upvoted Flutter issues

POST https://api.github.com/graphql
Accept: application/vnd.github+json
Authorization: Bearer ghp_12324
X-Request-Type: GraphQL

query ($after: String) {
  search(
    query: "repo:flutter/flutter is:open sort:reactions-+1-desc"
    type: ISSUE
    first: 100
    after: $after
  ) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        ... on Issue {
          comments {
            totalCount
          }
          createdAt
          labels(first: 20) {
            edges {
              node {
                name
              }
            }
          }
          number
          participants {
            totalCount
          }
          publishedAt
          reactions {
            totalCount
          }
          state
          title
        }
      }
    }
  }
}

### List reactions for a GitHub issue

GET https://api.github.com/repos/flutter/flutter/issues/14330/reactions?per_page=100&page=1
Accept: application/vnd.github+json
Authorization: Bearer ghp_12324
X-GitHub-Api-Version: 2022-11-28

### List timeline events for a GitHub issue

GET https://api.github.com/repos/flutter/flutter/issues/14330/timeline?per_page=100&page=1
Accept: application/vnd.github+json
Authorization: Bearer ghp_12324
X-GitHub-Api-Version: 2022-11-28
