name: github_insights
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-24.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.2.0
  intl: ^0.19.0
  path: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
