# Update GitHub Insights
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update GitHub insights

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Generate Flutter top issues
        run: dart run ./bin/github_insights.dart top_issues --repository flutter/flutter --top 1000 --output top_issues/flutter/flutter
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Dart SDK top issues
        run: dart run ./bin/github_insights.dart top_issues --repository dart-lang/sdk --top 1000 --output top_issues/dart-lang/sdk
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Dart language top issues
        run: dart run ./bin/github_insights.dart top_issues --repository dart-lang/language --top 1000 --output top_issues/dart-lang/language
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Dashboard
        run: dart run ./bin/github_insights.dart dashboard

      - name: Commit and push if data has changed
        id: commit-if-changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
          echo '::set-output name=has-changed::true'